# Generated by Django 4.2.4 on 2023-09-01 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("puput", "0008_alter_tagentrypage_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Search image",
            ),
        ),
        migrations.AddField(
            model_name="entrypage",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Search image",
            ),
        ),
        migrations.AlterField(
            model_name="entrypage",
            name="excerpt",
            field=models.TextField(
                help_text=(
                    "Entry excerpt to be displayed on entries list. If this field is"
                    " not filled, a truncate version of body text will be used."
                ),
                verbose_name="excerpt",
            ),
        ),
    ]
